"""add Department

Revision ID: 343f792e4ba3
Revises: 78ffc07cd77c
Create Date: 2024-04-24 16:54:04.390731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343f792e4ba3'
down_revision = '78ffc07cd77c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
