"""rename address

Revision ID: a910670a1c74
Revises: 1f35baea67c5
Create Date: 2024-04-24 17:00:19.852619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a910670a1c74'
down_revision = '1f35baea67c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  
    new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  
    new_column_name='address')
    # ### end Alembic commands ###
